# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

centered_kernel_matrix <- function(eval_points_1, eval_points_2, centering_grid, hurst_coef) {
    .Call(`_kefV1_centered_kernel_matrix`, eval_points_1, eval_points_2, centering_grid, hurst_coef)
}

centered_kernel_matrix_hd <- function(eval_points_1, eval_points_2, centering_grid, hurst_coef) {
    .Call(`_kefV1_centered_kernel_matrix_hd`, eval_points_1, eval_points_2, centering_grid, hurst_coef)
}

unnormalised_density_samples <- function(centered_kernel_mat_samples, lambda, weight_vec) {
    .Call(`_kefV1_unnormalised_density_samples`, centered_kernel_mat_samples, lambda, weight_vec)
}

unnormalised_density_grids <- function(centered_kernel_mat_grids, centered_kernel_self_grids, lambda, weight_vec) {
    .Call(`_kefV1_unnormalised_density_grids`, centered_kernel_mat_grids, centered_kernel_self_grids, lambda, weight_vec)
}

get_dens_wo_grid <- function(centered_kernel_mat_samples, samples, base_measure_weights, dimension, lambda, weight_vec) {
    .Call(`_kefV1_get_dens_wo_grid`, centered_kernel_mat_samples, samples, base_measure_weights, dimension, lambda, weight_vec)
}

get_dens <- function(centered_kernel_mat_samples, centered_kernel_mat_grids, centered_kernel_self_grids, samples, grids, base_measure_weights, dimension, lambda, weight_vec) {
    .Call(`_kefV1_get_dens`, centered_kernel_mat_samples, centered_kernel_mat_grids, centered_kernel_self_grids, samples, grids, base_measure_weights, dimension, lambda, weight_vec)
}

get_middle_points_grid <- function(min, samples, max) {
    .Call(`_kefV1_get_middle_points_grid`, min, samples, max)
}

get_s_function <- function(weight_vec, lambda, tau, centered_kernel_mat_samples, samples, base_measure_weights, dimension) {
    .Call(`_kefV1_get_s_function`, weight_vec, lambda, tau, centered_kernel_mat_samples, samples, base_measure_weights, dimension)
}

